//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monopoly
{
    using System;
    using System.Collections.Generic;
    
    public partial class KayitliOyunDetay
    {
        public int kayitliOyunID { get; set; }
        public string oyuncuID { get; set; }
        public int oyuncuPara { get; set; }
        public string hapisahenedeMi { get; set; }
        public int ciftZarAtmaSayisi { get; set; }
        public int hapishaneTurSayisi { get; set; }
        public int oyundakiKareYeri { get; set; }
        public string oyundanCekilme { get; set; }
        public int ID { get; set; }
        public int piyon { get; set; }
        public string renk { get; set; }
        public int kodestenCikKartiSayisi { get; set; }
    
        public virtual KayitliOyun KayitliOyun { get; set; }
    }
}
