//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monopoly
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MonopolyEntities5 : DbContext
    {
        public MonopolyEntities5()
            : base("name=MonopolyEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KamuFonuKartlari> KamuFonuKartlari { get; set; }
        public virtual DbSet<KartTipleri> KartTipleri { get; set; }
        public virtual DbSet<KayitliOyun> KayitliOyun { get; set; }
        public virtual DbSet<KayitliOyunDetay> KayitliOyunDetay { get; set; }
        public virtual DbSet<OyunAlani> OyunAlani { get; set; }
        public virtual DbSet<Piyonlar> Piyonlar { get; set; }
        public virtual DbSet<SansKartlari> SansKartlari { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TapularinSahipleri> TapularinSahipleri { get; set; }
        public virtual DbSet<TapuSenetleri> TapuSenetleri { get; set; }
        public virtual DbSet<OyunKurallari> OyunKurallari { get; set; }
    }
}
