//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monopoly
{
    using System;
    using System.Collections.Generic;
    
    public partial class OyunKurallari
    {
        public int initial_money { get; set; }
        public int initial_num_tapu { get; set; }
    }
}
