//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monopoly
{
    using System;
    using System.Collections.Generic;
    
    public partial class TapuSenetleri
    {
        public TapuSenetleri()
        {
            this.OyunAlani = new HashSet<OyunAlani>();
            this.TapularinSahipleri = new HashSet<TapularinSahipleri>();
        }
    
        public int id { get; set; }
        public string tapu_ismi { get; set; }
        public Nullable<int> fiyati { get; set; }
        public Nullable<int> arsa_kira { get; set; }
        public Nullable<int> ev1 { get; set; }
        public Nullable<int> ev2 { get; set; }
        public Nullable<int> ev3 { get; set; }
        public Nullable<int> ev4 { get; set; }
        public Nullable<int> otel_kira { get; set; }
        public Nullable<int> ev_maliyeti { get; set; }
        public Nullable<int> grup_sayisi { get; set; }
        public string renk { get; set; }
        public Nullable<int> kartTipi { get; set; }
    
        public virtual KartTipleri KartTipleri { get; set; }
        public virtual ICollection<OyunAlani> OyunAlani { get; set; }
        public virtual ICollection<TapularinSahipleri> TapularinSahipleri { get; set; }
    }
}
