//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monopoly
{
    using System;
    using System.Collections.Generic;
    
    public partial class TapularinSahipleri
    {
        public int id { get; set; }
        public int tapu_id { get; set; }
        public string oyuncu_id { get; set; }
        public int evSayisi { get; set; }
        public string ipotekliMi { get; set; }
    
        public virtual TapuSenetleri TapuSenetleri { get; set; }
    }
}
