//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonopolyServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class KartTipleri
    {
        public int id { get; set; }
        public string kart_tipi { get; set; }
    
        public virtual TapuSenetleri TapuSenetleri { get; set; }
    }
}
